### ISSUE TITLE
Navigator operation requested with a context that does not include a HybridNavigator.

### ISSUE THREAD

**Issue by jiangkun123** [weidian/hybrid_router#2]
Navigator operation requested with a context that does not include a HybridNavigator.

The context used to push or pop routes from the HybridNavigator must be that of a widget that is a descendant of a HybridNavigator widget.
请教一下  出现这个问题  该怎么结局呢   谢谢

**Comment by voiddog** [comment]
没有在 HybridNavigator 下面使用 HybridNavigator
